### ISSUE TITLE
Using nested var declarations within each?

### ISSUE THREAD

**Issue by oleersoy** [outpunk/postcss-each#11]
Hi,

I have the following css
```css
:root {
  --percentage-variation2:  22%;
  --percentage-variation1: 10%;
}
:root {
  --color-primary:         #0275d8;
  --color-success:         #5cb85c;
  --color-info:            #5bc0de;
  --color-warning:         #f0ad4e;
  --color-danger:          #d9534f;
}

:root {
  --color-primary-100: color(var(--color-primary) lightness(var(--percentage-variation2)));
  --color-primary-300: color(var(--color-primary) lightness(var(--percentage-variation1)));
  --color-primary-500: var(--color-primary);
  --color-primary-700: color(var(--color-primary) blackness(var(--percentage-variation1)));
  --color-primary-900: color(var(--color-primary) blackness(var(--percentage-variation2)));

}


@each $brand in primary {
    .u-color-background-$brand {
      background-color: var(--color-$brand-100);
    }
}
```
On this I run the following sequence:
```js
var processors = [postcss_import, postcss_each, postcss_custom_properties, postcss_color_function, postcss_calc, autoprefixer];
```
However the result is:

``` css
.u-color-background-primary {
    background-color: $brand-100
}
``` 
If I run the same loop like this (Without the `-100` at the end):
``` css
@each $brand in primary {
    .u-color-background-$brand {
      background-color: var(--color-$brand);
    }
}
```

I get:
``` css
.u-color-background-primary {
    background-color: #0275d8
}
```
So there seems to be an issue with the `-100` being included.  If I use the variables that include the `-100` outside of the loop they resolve OK.  For example:
``` css
h1 {
  color: var(--color-primary-100);
}
```
Resolves to:
```css
h1 {
  color: rgb(1, 60, 111);
}
```
Thoughts?

Cheers,
Ole

**Comment by outpunk** [comment]
Hi,

That's happening because the parser is trying to find the `$brand-100` variable instead of `$brand`.
Just use parentheses: 
```css
@each $brand in primary {
    .u-color-background-$brand {
      background-color: var(--color-$(brand)-100);
    }
}
```
