### ISSUE TITLE
Problem iterating through multiple variables

### ISSUE THREAD

**Issue by Dylan-Chapman** [outpunk/postcss-each#12]
The example given by the documentation

```css
@each $animal, $color in (puma, black), (sea-slug, blue) {
	.$(animal)-icon {
		background-image: url('/images/$(animal).png');
		border: 2px solid $color;
	}
}
```

Outputs as

```css
.puma-icon {
	background-image: url('/images/puma.png');
	border: 2px solid sea-slug
}

.black-icon {
	background-image: url('/images/black.png');
	border: 2px solid blue
}
```

This doesn't seem like the intended behavior. Any way around this?

**Comment by outpunk** [comment]
I've just checked this. This is a bug, will fix tomorrow.

**Comment by outpunk** [comment]
@Dylan-Chapman Hi! Sorry for keeping you waiting. The example in the readme file was wrong. I've just fixed it. Here is the correct one:
```css
@each $animal, $color in (puma, sea-slug), (black, blue) {
  .$(animal)-icon {
    background-image: url('/images/$(animal).png');
    border: 2px solid $color;
  }
}
```

```css
.puma-icon {
  background-image: url('/images/puma.png');
  border: 2px solid black;
}
.sea-slug-icon {
  background-image: url('/images/sea-slug.png');
  border: 2px solid blue;
}
```
