### ISSUE TITLE
Unexpected content result

### ISSUE THREAD

**Issue by oleersoy** [outpunk/postcss-each#13]
Hi,

I have a loop that looks like this:
```css
@each $fontSize in 100, 200, 300, 400, 500, 600, 700, 800 900 {
  @each $fontWeight in 100, 200, 300, 400, 500, 600, 700, 800 900 {
    .Display--fs$(fontSize)fw$(fontWeight) {
      font-size: var(--display-size-$(fontSize));
      font-weight: $(fontWeight);
       }
    }
}
```
When I run it the initial output is OK:
```css
.Display--fs100fw100 {

    font-size: 3.5rem;

    font-weight: 100
}
```

Side Note: Should the last semicolon be stripped?

However when the loop gets to the end (900), I get output like this:
```css
.Display--fs800 900fw100 {

    font-size:  900;

    font-size: 7.0rem;

    font-weight: 100

...

.Display--fs800 900fw200 {

    font-size:  900;

    font-size: 7.0rem;

    font-weight: 200
}

}

...

.Display--fs800 900fw300 {

    font-size:  900;

    font-size: 7.0rem;

    font-weight: 300
}

```

LAST SEGMENT

.Display--fs100fw800 900 {

    font-size: 3.5rem;

    font-weight: 800 900
}

.Display--fs200fw800 900 {

    font-size: 4.0rem;

    font-weight: 800 900
}

.Display--fs300fw800 900 {

    font-size: 4.5rem;

    font-weight: 800 900
}

.Display--fs400fw800 900 {

    font-size: 5.0rem;

    font-weight: 800 900
}

.Display--fs500fw800 900 {

    font-size: 5.5rem;

    font-weight: 800 900
}

.Display--fs600fw800 900 {

    font-size: 6.0rem;

    font-weight: 800 900
}

.Display--fs700fw800 900 {

    font-size: 6.5rem;

    font-weight: 800 900
}

.Display--fs800 900fw800 900 {

    font-size:  900;

    font-size: 7.0rem;

    font-weight: 800 900
}

The github repository for the component can be found here:
https://github.com/superfly-css/superfly-css-component-display

Just clone and run `gulp build:css` to see the result in the `target/main/css/index.css` file.

Cheers,
Ole
