### ISSUE TITLE
Accessing values from postcss-map

### ISSUE THREAD

**Issue by aviemet** [outpunk/postcss-each#22]
I am trying to build a custom grid definition, would like to keep settings in a yaml file, something like this:

```
# settings.yml
breakpoints:
  small: 360px
  medium: 600px
  large: 1180px
  xlarge: 1400px

grid:
  columns: 12
```

if I iterate over with each, is there a way to get the key? I'm trying to do something like this:

```
@for $i from 1 to map(settings, grid, columns) {
  @each $name, $width in map(settings, breakpoints){
    @media screen and (max-width: $(width)){
      .$(name)-$(i){
        ...
      }
    }
  }
}
```

Which outputs:

```
@media screen and (max-width: 0){
  .row .[object Object]-1{
    ...
  }
}
```

Is this at all possible?

I tried storing values in parens: `- (small, 360px)` which gave some strange results.
