### ISSUE TITLE
Who remove '*int' from vals?

### ISSUE THREAD

**Issue by verybigman** [outpunk/postcss-each#4]
If val in array contain `int`:

``` css
@each name in print, olol {
     background-image: url('icon_tool_$(name).svg');
}
```
Result:
 ``` css
background-image: url('icon_tool_pr.svg');
background-image: url('icon_tool_olol.svg');
```
