### ISSUE TITLE
Support for nested @each loops

### ISSUE THREAD

**Issue by rtsao** [outpunk/postcss-each#6]
Any plans for support for nested `@each` iteration?

For example in Sass:
```sass
@each $foo in ab, cd {
  .#{$foo} {
    @each $bar in ef, gh {
      #{$bar}: 10px;
    }
  }
}
```
```css
.ab {
  ef: 10px;
  gh: 10px;
}

.cd {
  ef: 10px;
  gh: 10px;
}
```

See: https://github.com/outpunk/postcss-each/pull/7/files
